server:
  port: 5590
spring:
  application:
    name: cloud-search
  data: 
    solr:
      host: http://192.168.1.146:8080/solr
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**,*.md
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpleoa?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
    password: 52LDforever