spring:
  main: 
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      # 显示sql
      sql: 
        show: true
    # 配置数据源
    datasource:
      names: ds1,ds2,ds3
      ds1: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sharding-jdbc-db?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      ds2: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/sharding-jdbc-db?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
      ds3: 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/sharding-jdbc-db?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
    # 配置默认数据源ds1 默认数据源,主要用于写
    sharding: 
      default-data-source-name: ds1
      # 分库分表
      tables:
        # 分布式主键生成策略列名
        t_order.key-generator.column: id
        # 分布式主键生成策略
        key-generator.type: SNOWFLAKE
        # 多数据源$->{0..N}.逻辑表名$->{0..N} 相同表
        t_order.actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
        # 多数据源$->{0..N}.逻辑表名$->{0..N} 不同表
        # t_order.actual-data-nodes: ds0.t_order$->{0..1},ds1.t_order$->{2..4}
        # 单数据源的配置方式,单库分表
        # t_order.actual-data-nodes: ds0.t_order$->{0..4}
        # 全部手动指定
        # t_order.actual-data-nodes=ds0.t_order0,ds1.t_order0,ds0.t_order1,ds1.t_order1
    masterslave: 
      # 配置主从名称
      name: ms
      # 设置主库master,负责数据的写入
      master-data-source-name: ds1
      # 配置从库slave节点
      slave-data-source-names: ds2,ds3
      # 配置slave节点的负载均衡均衡策略,采用轮询机制
      load-balance-algorithm-type: round_robin